dazzleduck_server = {
    http.port = 8081
    http.host = "0.0.0.0"
    http.authentication = "jwt"
    jwt_token.claims.generate.headers = [database,schema,x-dd-table,x-dd-filter,x-dd-access,x-dd-path,x-dd-function,x-dd-access-type,x-dd-variables]
    http.allow-origin = ["https://dazzleduck-ui.netlify.app"]
    http.tls {
        # Default (will be overridden by --conf tls=true)
        enabled = false

        private-key {
            pem {
                key.resource.resource-path = "key-pkcs8.pem"
                cert-chain.resource.resource-path = "chain.pem"
            }
        }
        trust {
            pem {
                certificates.resource.resource-path = "ca-bundle.pem"
            }
        }
    }
}